int _abs(int n);
int _isalpha(int c);
int _islower(int c);
int _putchar(char c);
int add(int a, int b);
int print_last_digit(int n);
int print_sign(int n);
void jack_bauer(void);
void print_alphabet(void);
void print_alphabet_x10(void);
void print_to_98(int n);
void times_table(void);
